/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PlayRouteImport } from './routes/play'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicPaystackWebhookRouteImport } from './routes/api/public/paystack-webhook'
import { Route as ApiGamePublicStateRouteImport } from './routes/api/game/public-state'
import { Route as ApiGamePlayRouteImport } from './routes/api/game/play'
import { Route as ApiGameHistoryRouteImport } from './routes/api/game/history'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthSignoutRouteImport } from './routes/api/auth/signout'
import { Route as ApiAuthSigninRouteImport } from './routes/api/auth/signin'
import { Route as ApiAuthProfilesIndexRouteImport } from './routes/api/auth/profiles/index'
import { Route as ApiAuthProfilesMeRouteImport } from './routes/api/auth/profiles/me'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaystackWebhookRoute =
  ApiPublicPaystackWebhookRouteImport.update({
    id: '/api/public/paystack-webhook',
    path: '/api/public/paystack-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGamePublicStateRoute = ApiGamePublicStateRouteImport.update({
  id: '/api/game/public-state',
  path: '/api/game/public-state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGamePlayRoute = ApiGamePlayRouteImport.update({
  id: '/api/game/play',
  path: '/api/game/play',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGameHistoryRoute = ApiGameHistoryRouteImport.update({
  id: '/api/game/history',
  path: '/api/game/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignoutRoute = ApiAuthSignoutRouteImport.update({
  id: '/api/auth/signout',
  path: '/api/auth/signout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSigninRoute = ApiAuthSigninRouteImport.update({
  id: '/api/auth/signin',
  path: '/api/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfilesIndexRoute = ApiAuthProfilesIndexRouteImport.update({
  id: '/api/auth/profiles/',
  path: '/api/auth/profiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthProfilesMeRoute = ApiAuthProfilesMeRouteImport.update({
  id: '/api/auth/profiles/me',
  path: '/api/auth/profiles/me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/play': typeof PlayRoute
  '/terms': typeof TermsRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/game/history': typeof ApiGameHistoryRoute
  '/api/game/play': typeof ApiGamePlayRoute
  '/api/game/public-state': typeof ApiGamePublicStateRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/auth/profiles/me': typeof ApiAuthProfilesMeRoute
  '/api/auth/profiles/': typeof ApiAuthProfilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/play': typeof PlayRoute
  '/terms': typeof TermsRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/game/history': typeof ApiGameHistoryRoute
  '/api/game/play': typeof ApiGamePlayRoute
  '/api/game/public-state': typeof ApiGamePublicStateRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/auth/profiles/me': typeof ApiAuthProfilesMeRoute
  '/api/auth/profiles': typeof ApiAuthProfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api-docs': typeof ApiDocsRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/play': typeof PlayRoute
  '/terms': typeof TermsRoute
  '/api/auth/signin': typeof ApiAuthSigninRoute
  '/api/auth/signout': typeof ApiAuthSignoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/game/history': typeof ApiGameHistoryRoute
  '/api/game/play': typeof ApiGamePlayRoute
  '/api/game/public-state': typeof ApiGamePublicStateRoute
  '/api/public/paystack-webhook': typeof ApiPublicPaystackWebhookRoute
  '/api/auth/profiles/me': typeof ApiAuthProfilesMeRoute
  '/api/auth/profiles/': typeof ApiAuthProfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api-docs'
    | '/auth'
    | '/history'
    | '/play'
    | '/terms'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/game/history'
    | '/api/game/play'
    | '/api/game/public-state'
    | '/api/public/paystack-webhook'
    | '/api/auth/profiles/me'
    | '/api/auth/profiles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api-docs'
    | '/auth'
    | '/history'
    | '/play'
    | '/terms'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/game/history'
    | '/api/game/play'
    | '/api/game/public-state'
    | '/api/public/paystack-webhook'
    | '/api/auth/profiles/me'
    | '/api/auth/profiles'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api-docs'
    | '/auth'
    | '/history'
    | '/play'
    | '/terms'
    | '/api/auth/signin'
    | '/api/auth/signout'
    | '/api/auth/signup'
    | '/api/game/history'
    | '/api/game/play'
    | '/api/game/public-state'
    | '/api/public/paystack-webhook'
    | '/api/auth/profiles/me'
    | '/api/auth/profiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiDocsRoute: typeof ApiDocsRoute
  AuthRoute: typeof AuthRoute
  HistoryRoute: typeof HistoryRoute
  PlayRoute: typeof PlayRoute
  TermsRoute: typeof TermsRoute
  ApiAuthSigninRoute: typeof ApiAuthSigninRoute
  ApiAuthSignoutRoute: typeof ApiAuthSignoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiGameHistoryRoute: typeof ApiGameHistoryRoute
  ApiGamePlayRoute: typeof ApiGamePlayRoute
  ApiGamePublicStateRoute: typeof ApiGamePublicStateRoute
  ApiPublicPaystackWebhookRoute: typeof ApiPublicPaystackWebhookRoute
  ApiAuthProfilesMeRoute: typeof ApiAuthProfilesMeRoute
  ApiAuthProfilesIndexRoute: typeof ApiAuthProfilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paystack-webhook': {
      id: '/api/public/paystack-webhook'
      path: '/api/public/paystack-webhook'
      fullPath: '/api/public/paystack-webhook'
      preLoaderRoute: typeof ApiPublicPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/public-state': {
      id: '/api/game/public-state'
      path: '/api/game/public-state'
      fullPath: '/api/game/public-state'
      preLoaderRoute: typeof ApiGamePublicStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/play': {
      id: '/api/game/play'
      path: '/api/game/play'
      fullPath: '/api/game/play'
      preLoaderRoute: typeof ApiGamePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/game/history': {
      id: '/api/game/history'
      path: '/api/game/history'
      fullPath: '/api/game/history'
      preLoaderRoute: typeof ApiGameHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signout': {
      id: '/api/auth/signout'
      path: '/api/auth/signout'
      fullPath: '/api/auth/signout'
      preLoaderRoute: typeof ApiAuthSignoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signin': {
      id: '/api/auth/signin'
      path: '/api/auth/signin'
      fullPath: '/api/auth/signin'
      preLoaderRoute: typeof ApiAuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profiles/': {
      id: '/api/auth/profiles/'
      path: '/api/auth/profiles'
      fullPath: '/api/auth/profiles/'
      preLoaderRoute: typeof ApiAuthProfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/profiles/me': {
      id: '/api/auth/profiles/me'
      path: '/api/auth/profiles/me'
      fullPath: '/api/auth/profiles/me'
      preLoaderRoute: typeof ApiAuthProfilesMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiDocsRoute: ApiDocsRoute,
  AuthRoute: AuthRoute,
  HistoryRoute: HistoryRoute,
  PlayRoute: PlayRoute,
  TermsRoute: TermsRoute,
  ApiAuthSigninRoute: ApiAuthSigninRoute,
  ApiAuthSignoutRoute: ApiAuthSignoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiGameHistoryRoute: ApiGameHistoryRoute,
  ApiGamePlayRoute: ApiGamePlayRoute,
  ApiGamePublicStateRoute: ApiGamePublicStateRoute,
  ApiPublicPaystackWebhookRoute: ApiPublicPaystackWebhookRoute,
  ApiAuthProfilesMeRoute: ApiAuthProfilesMeRoute,
  ApiAuthProfilesIndexRoute: ApiAuthProfilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
